#!/usr/bin/env python3
import argparse
import os
import re
import sys
from collections import defaultdict

SKIP_DIRS = {'node_modules', '.git', '__pycache__', 'venv', '.venv', '.env', 'dist', 'build', 'target', '.next', '.cache'}
SKIP_EXTS = {'.png', '.jpg', '.jpeg', '.gif', '.ico', '.svg', '.woff', '.woff2', '.eot', '.ttf', '.otf',
             '.pdf', '.zip', '.tar', '.gz', '.bin', '.exe', '.dll', '.so', '.dylib',
             '.o', '.obj', '.pyc', '.pyo', '.lock'}

PATTERNS = {
    'python': [
        (r"os\.getenv\s*\(\s*['\"](\w+)['\"]", 1),
        (r"os\.environ\.get\s*\(\s*['\"](\w+)['\"]", 1),
        (r"os\.environ\s*\[\s*['\"](\w+)['\"]", 1),
    ],
    'node': [
        (r"process\.env\.(\w+)", 1),
    ],
    'go': [
        (r"os\.Getenv\s*\(\s*['\"](\w+)['\"]", 1),
        (r"os\.LookupEnv\s*\(\s*['\"](\w+)['\"]", 1),
    ],
    'rust': [
        (r"std::env::var\s*\(\s*['\"](\w+)['\"]", 1),
        (r"env!\s*\(\s*['\"](\w+)['\"]", 1),
    ],
    'shell': [
        (r'\$([A-Z_][A-Z_0-9]*)', 1),
    ],
    'docker': [
        (r'\$([A-Z_][A-Z_0-9]*)', 1),
    ],
    'yaml': [
        (r'\$\{?([A-Z_][A-Z_0-9]*)\}?', 1),
    ],
    'general': [
        (r'\.env\.(\w+)', 1),
    ],
}

FILE_TYPE_MAP = {
    '.py': 'python',
    '.js': 'node', '.jsx': 'node', '.ts': 'node', '.tsx': 'node', '.mjs': 'node', '.cjs': 'node',
    '.rs': 'rust',
    '.go': 'go',
    '.sh': 'shell', '.bash': 'shell', '.zsh': 'shell',
    'dockerfile': 'docker', '.dockerfile': 'docker',
    '.yml': 'yaml', '.yaml': 'yaml',
}

DEFAULT_PLACEHOLDERS = {
    'DATABASE_URL': 'postgresql://user:pass@localhost:5432/db',
    'API_KEY': 'your-api-key-here',
    'SECRET_KEY': 'your-secret-key-here',
    'DEBUG': 'false',
    'PORT': '3000',
    'HOST': '0.0.0.0',
    'NODE_ENV': 'development',
    'PYTHON_ENV': 'development',
    'REDIS_URL': 'redis://localhost:6379',
    'CELERY_BROKER_URL': 'redis://localhost:6379/0',
    'LOG_LEVEL': 'info',
    'AWS_ACCESS_KEY_ID': 'your-access-key',
    'AWS_SECRET_ACCESS_KEY': 'your-secret-key',
    'SENDGRID_API_KEY': 'your-sendgrid-key',
    'STRIPE_API_KEY': 'sk_test_...',
    'JWT_SECRET': 'your-jwt-secret',
    'EMAIL_HOST': 'smtp.example.com',
    'EMAIL_PORT': '587',
    'EMAIL_USER': 'user@example.com',
    'EMAIL_PASSWORD': 'your-email-password',
}


def guess_placeholder(var_name):
    upper = var_name.upper()
    if upper in DEFAULT_PLACEHOLDERS:
        return DEFAULT_PLACEHOLDERS[upper]
    suffix_map = {
        '_URL': 'http://localhost:8080',
        '_HOST': 'localhost',
        '_PORT': '8080',
        '_KEY': 'your-key',
        '_SECRET': 'your-secret',
        '_PASSWORD': 'your-password',
        '_USER': 'user',
        '_USERNAME': 'user',
        '_EMAIL': 'user@example.com',
        '_TOKEN': 'your-token',
        '_ID': 'your-id',
        '_DIR': '/path/to/dir',
        '_PATH': '/path/to/file',
        '_FILE': '/path/to/file',
        '_NAME': 'your-name',
        '_VERSION': '1.0.0',
    }
    for suffix, placeholder in suffix_map.items():
        if upper.endswith(suffix):
            return placeholder
    return f'your-{var_name.lower().replace("_", "-")}-here'


def scan_file(filepath):
    results = []
    _, ext = os.path.splitext(filepath)
    basename = os.path.basename(filepath).lower()

    file_type = FILE_TYPE_MAP.get(ext)
    if basename == 'dockerfile' or basename.endswith('.dockerfile'):
        file_type = 'docker'
    if file_type is None and ext in ('.yml', '.yaml'):
        file_type = 'yaml'

    if file_type is None:
        if ext == '.sh':
            file_type = 'shell'
        else:
            return results

    patterns = PATTERNS.get(file_type, [])

    try:
        with open(filepath, 'r', encoding='utf-8', errors='replace') as f:
            content = f.read()
    except Exception:
        return results

    for pattern, group in patterns:
        for match in re.finditer(pattern, content, re.MULTILINE):
            var_name = match.group(group)
            results.append(var_name)

    return results


def scan_codebase(root):
    env_vars = defaultdict(lambda: {'files': set(), 'defaults': []})

    for dirpath, dirnames, filenames in os.walk(root):
        dirnames[:] = [d for d in dirnames if d not in SKIP_DIRS]
        for f in filenames:
            _, ext = os.path.splitext(f)
            if ext in SKIP_EXTS:
                continue
            filepath = os.path.join(dirpath, f)
            relpath = os.path.relpath(filepath, root)
            vars_found = scan_file(filepath)
            for var in vars_found:
                env_vars[var]['files'].add(relpath)

    return dict(env_vars)


def write_env_example(env_vars, output_path, stdout_mode):
    lines = [
        '# Environment Variables',
        '# Auto-generated by env-doc',
        '',
    ]

    for var_name in sorted(env_vars.keys()):
        info = env_vars[var_name]
        files = sorted(info['files'])
        placeholder = guess_placeholder(var_name)

        lines.append(f'{var_name}={placeholder}')
        lines.append(f'# Found in: {", ".join(files)}')

        defaults = info.get('defaults', [])
        if defaults:
            for d in defaults:
                lines.append(f'# Default: {d}')

        lines.append('')

    content = '\n'.join(lines)

    if stdout_mode:
        print(content)
    else:
        with open(output_path, 'w', encoding='utf-8') as f:
            f.write(content)
        print(f"Wrote {output_path}")


def main():
    parser = argparse.ArgumentParser(description='Auto-generate .env.example from your codebase.')
    parser.add_argument('--path', default=os.getcwd(), help='Project root directory')
    parser.add_argument('--output', '-o', default='.env.example', help='Output file (default: .env.example)')
    parser.add_argument('--stdout', action='store_true', help='Print to stdout instead of writing')
    args = parser.parse_args()

    root = os.path.abspath(args.path)

    if not os.path.isdir(root):
        print(f"Path does not exist: {root}", file=sys.stderr)
        sys.exit(1)

    print(f"Scanning {root}...")
    env_vars = scan_codebase(root)

    if not env_vars:
        print("No environment variables found.")
        sys.exit(0)

    file_count = sum(len(v['files']) for v in env_vars.values())
    print(f"Found {len(env_vars)} unique env vars across {file_count} file(s)")

    write_env_example(env_vars, args.output, args.stdout)


if __name__ == '__main__':
    main()
