#!/usr/bin/env python3
"""
plugin-hot-reload -- Python CLI + file watcher that auto-reloads Roblox Studio plugin code.
"""

import argparse
import os
import signal
import sys
import time

########################################
# Signal file helpers
########################################


def touch_signal_file(output_dir: str, package_name: str) -> str:
    """Create/update the signal file that the Luau wrapper watches."""
    signal_dir = os.path.join(output_dir, package_name + "-reload-signal")
    os.makedirs(signal_dir, exist_ok=True)
    signal_path = os.path.join(signal_dir, "__reload_signal.rbxm")
    with open(signal_path, "w", encoding="utf-8") as f:
        f.write("signal")
    return signal_path


########################################
# Luau wrapper generation
########################################


LUA_SCRIPT_TEMPLATE = """-- Generated by plugin-hot-reload
-- DO NOT EDIT -- regenerated automatically

local Plugin = plugin or getfenv().plugin
local toolbar = Plugin:CreateToolbar("{plugin_name}")
local reloadButton = toolbar:CreateButton(
    "Reload",
    "Reload plugin code ({plugin_name})",
    ""
)

local Reloader = {{}}
Reloader.modules = {{}}
Reloader.watchFile = script.Parent:WaitForChild("{signal_folder_name}"):WaitForChild("__reload_signal")

local function reloadAll()
    for path, _ in pairs(Reloader.modules) do
        Reloader.modules[path] = nil
    end
    local success, err = pcall(function()
        require({entry_require})
    end)
    if not success then
        warn("Reload failed:", err)
        return false
    end
    return true
end

reloadButton.Click:Connect(reloadAll)

task.spawn(function()
    while true do
        local success, changed = pcall(function()
            return Reloader.watchFile:GetAttribute("Changed")
        end)
        if success and changed then
            pcall(function()
                Reloader.watchFile:SetAttribute("Changed", false)
            end)
            reloadAll()
        end
        task.wait(0.5)
    end
end)

return Reloader
"""


def find_entry_point(watch_dirs):
    """Find the main init/plugin file across all watch directories."""
    candidates = ["init.luau", "plugin.luau", "main.luau"]
    for watch_dir in watch_dirs:
        for name in candidates:
            path = os.path.join(watch_dir, name)
            if os.path.isfile(path):
                return path
    return None


def generate_wrapper(output_dir, package_name, watch_dirs):
    """Write the Luau wrapper script."""
    signal_folder_name = package_name + "-reload-signal"

    entry_path = find_entry_point(watch_dirs)
    if entry_path:
        entry_dir = os.path.dirname(entry_path)
        entry_require = f'script.Parent.{os.path.relpath(entry_path, entry_dir).replace(os.sep, ".").replace(".luau", "")}'
    else:
        entry_require = ""

    script_content = LUA_SCRIPT_TEMPLATE.format(
        plugin_name=package_name,
        signal_folder_name=signal_folder_name,
        entry_require=entry_require,
    )

    wrapper_filename = f"{package_name}-reload.luau"
    wrapper_path = os.path.join(output_dir, wrapper_filename)
    with open(wrapper_path, "w", encoding="utf-8") as f:
        f.write(script_content)

    return wrapper_path


########################################
# File watcher
########################################


def scan_files(directories):
    """Walk directories and return dict of relative_path -> mtime."""
    files = {}
    for directory in directories:
        if not os.path.isdir(directory):
            continue
        for root, _, filenames in os.walk(directory):
            for filename in filenames:
                full = os.path.join(root, filename)
                rel = os.path.relpath(full, directory)
                try:
                    files[(directory, rel)] = os.path.getmtime(full)
                except OSError:
                    pass
    return files


def format_rel(directory, rel_path):
    """Format a path relative to the watch directory for display."""
    return os.path.join(os.path.basename(directory), rel_path).replace("\\", "/")


def watch_loop(watch_dirs, output_dir, package_name, interval):
    """Poll directories for changes and emit signals."""
    print(f"\n=== plugin-hot-reload -- watching {', '.join(watch_dirs)}")
    print("=" * 56)
    print()

    wrapper_path = generate_wrapper(output_dir, package_name, watch_dirs)
    wrapper_name = os.path.basename(wrapper_path)
    print(f"  >> Generated wrapper: {wrapper_name}")

    prev_state = scan_files(watch_dirs)
    file_count = len(prev_state)
    unique_dirs = set(directory for directory, _ in prev_state)
    dir_count = len(unique_dirs)

    print(f"  >> Watching {file_count} files in {dir_count} directories")
    print()

    # Touch initial signal file so wrapper can find it
    signal_path = touch_signal_file(output_dir, package_name)
    print(f"  [{_timestamp()}] Connected to Roblox Studio")
    print()

    reload_count = 0
    error_count = 0
    running = True

    def handle_interrupt(*_):
        nonlocal running
        running = False

    original_sigint = signal.signal(signal.SIGINT, handle_interrupt)

    try:
        while running:
            current_state = scan_files(watch_dirs)
            changed = False

            # Check for new and modified files
            all_keys = set(prev_state.keys()) | set(current_state.keys())
            for key in all_keys:
                prev_mtime = prev_state.get(key)
                curr_mtime = current_state.get(key)

                if prev_mtime is None and curr_mtime is not None:
                    directory, rel = key
                    print(f"  [{_timestamp()}] New file: {format_rel(directory, rel)} -> Auto-loaded")
                    changed = True
                elif prev_mtime is not None and curr_mtime is None:
                    directory, rel = key
                    print(f"  [{_timestamp()}] Deleted: {format_rel(directory, rel)}")
                elif prev_mtime is not None and curr_mtime is not None and prev_mtime != curr_mtime:
                    directory, rel = key
                    print(f"  [{_timestamp()}] Modified: {format_rel(directory, rel)} -> Reloaded")
                    changed = True

            if changed:
                reload_count += 1
                touch_signal_file(output_dir, package_name)

            prev_state = current_state

            try:
                time.sleep(interval)
            except (KeyboardInterrupt, SystemExit):
                break

    except (KeyboardInterrupt, SystemExit):
        pass
    finally:
        signal.signal(signal.SIGINT, original_sigint)
        print()
        print(f"  == Session: {reload_count} reloads, {error_count} errors, {file_count} files watched")
        print()


def _timestamp():
    return time.strftime("%H:%M:%S")


########################################
# CLI entry point
########################################


def parse_watch_paths(raw):
    """Split comma-separated or space-separated watch paths."""
    if not raw:
        return []
    paths = []
    for part in raw.replace(",", " ").split():
        part = part.strip()
        if part:
            paths.append(os.path.abspath(part))
    return paths


def main():
    parser = argparse.ArgumentParser(
        prog="plugin-hot-reload",
        description="Auto-reload Roblox Studio plugin code when files change on disk.",
    )
    parser.add_argument(
        "-w", "--watch",
        required=True,
        help="Directory(s) to watch (comma-separated or multiple args)",
        nargs="+",
    )
    parser.add_argument(
        "-o", "--output",
        default=".",
        help="Output directory for generated wrapper (default: current dir)",
    )
    parser.add_argument(
        "-i", "--interval",
        type=float,
        default=2.0,
        help="Poll interval in seconds (default: 2)",
    )
    parser.add_argument(
        "-n", "--package-name",
        default=None,
        help="Plugin name for generated script (default: basename of first watch dir)",
    )
    parser.add_argument(
        "--generate-only",
        action="store_true",
        help="Only generate the wrapper script without watching",
    )

    args = parser.parse_args()

    # Flatten watch paths in case nargs gives nested lists
    watch_dirs = []
    for item in args.watch:
        watch_dirs.extend(parse_watch_paths(item))
    watch_dirs = list(dict.fromkeys(watch_dirs))  # dedupe preserving order

    output_dir = os.path.abspath(args.output)
    os.makedirs(output_dir, exist_ok=True)

    if args.package_name:
        package_name = args.package_name
    else:
        package_name = os.path.basename(watch_dirs[0].rstrip(os.sep))

    if args.generate_only:
        wrapper_path = generate_wrapper(output_dir, package_name, watch_dirs)
        wrapper_name = os.path.basename(wrapper_path)
        print(f">> Generated wrapper: {wrapper_name}")
        signal_path = touch_signal_file(output_dir, package_name)
        signal_name = os.path.basename(signal_path)
        print(f">> Generated signal file: {os.path.join(os.path.basename(os.path.dirname(signal_path)), signal_name)}")
        return

    watch_loop(watch_dirs, output_dir, package_name, args.interval)


if __name__ == "__main__":
    main()
